"""crear modulo de seguridad

Revision ID: a9dd2cc8750c
Revises: 
Create Date: 2026-09-01 20:59:36.010534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9dd2cc8750c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opcion_menu',
    sa.Column('id_opcion_menu', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ruta', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('icono', sa.String(length=80), nullable=True),
    sa.Column('id_padre', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('orden', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_padre'], ['opcion_menu.id_opcion_menu'], ),
    sa.PrimaryKeyConstraint('id_opcion_menu'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ruta')
    )
    with op.batch_alter_table('opcion_menu', schema=None) as batch_op:
        batch_op.create_index('ix_opcion_menu_padre_orden', ['id_padre', 'orden'], unique=False)

    op.create_table('perfil',
    sa.Column('id_perfil', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('permiso',
    sa.Column('id_permiso', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('celular', sa.String(length=9), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('creado_por', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modificado_por', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('dni')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('uq_usuario_correo_lower', [sa.literal_column('lower(correo)')], unique=True)

    op.create_table('auditoria',
    sa.Column('id_auditoria', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_usuario', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id_perfil', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('id_registro', sa.String(length=100), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil.id_perfil'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_auditoria')
    )
    op.create_table('perfil_opcion_menu',
    sa.Column('id_perfil', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_opcion_menu', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_opcion_menu'], ['opcion_menu.id_opcion_menu'], ),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_perfil', 'id_opcion_menu')
    )
    op.create_table('perfil_permiso',
    sa.Column('id_perfil', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_permiso', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil.id_perfil'], ),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id_permiso'], ),
    sa.PrimaryKeyConstraint('id_perfil', 'id_permiso')
    )
    op.create_table('usuario_perfil',
    sa.Column('id_usuario', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_perfil', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('asignado_por', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modificado_por', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('modificado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil.id_perfil'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuario.id_usuario'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_perfil')
    )
    op.create_table('sesion',
    sa.Column('id_sesion', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('id_perfil', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario', 'id_perfil'], ['usuario_perfil.id_usuario', 'usuario_perfil.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_sesion'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sesion')
    op.drop_table('usuario_perfil')
    op.drop_table('perfil_permiso')
    op.drop_table('perfil_opcion_menu')
    op.drop_table('auditoria')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('uq_usuario_correo_lower')

    op.drop_table('usuario')
    op.drop_table('permiso')
    op.drop_table('perfil')
    with op.batch_alter_table('opcion_menu', schema=None) as batch_op:
        batch_op.drop_index('ix_opcion_menu_padre_orden')

    op.drop_table('opcion_menu')
    # ### end Alembic commands ###
